theme_advanced_buttons1 : "cut,copy,paste,pastetext,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,preview,fullscreen,|,charmap,media,|,visualchars,blockquote,bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist"
theme_advanced_buttons2 : ""
theme_advanced_buttons3 : ""
theme_advanced_buttons4 : ""
theme_advanced_toolbar_location : "top"
theme_advanced_toolbar_align : "left"
theme_advanced_statusbar_location : "top"
theme_advanced_resizing : false
